### ISSUE TITLE
Error formato de correo electronico

### ISSUE THREAD

**Issue by SantiGacia** [SantiGacia/Homeint#1]
Error sucede en candidato-edi candidato, empleado-edi empleado

![Correo error](https://user-images.githubusercontent.com/89488595/136141696-f3b54daa-a5aa-44a8-a5bf-2b18fb027004.PNG)

**Comment by JesusMorales34** [comment]
En teoría, agregando esta condición al finalizar la línea de las propiedades

pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"
